### ISSUE TITLE
MultiChainLadder fails

### ISSUE THREAD

**Issue by chiefmurph** [mages/ChainLadder#22]
MultiChainLadder(list(GenIns, GenIns))
fails with lapack error
 Error in solve(sigma, tol = solvetol) : 
  Lapack routine dsptrf returned error code 1 

I am getting systemfit-generated errors with other triangles as well.

**Comment by actuaryzhang** [comment]
This is because the input triangles are identical, and so are the residuals. The covariance between the two sets of residuals are singular, thus not invertible. So it is not a bug. If the input triangles are not the same, there won't be such problems. 

GenIns2 <- GenIns
idx <- !is.na(GenIns2)
GenIns2[idx] <- GenIns2[idx] + rnorm(sum(idx))
MultiChainLadder(list(GenIns, GenIns2))

**Comment by chiefmurph** [comment]
That makes sense and easy to trap, but unfortunately not the likely cause of systemfit failures in practice. It would be nice to provide a more informative message when MultiChainLadder fails. I will try to find a better, "real life" example.
